"""Marketplace schemas

Revision ID: 3b177c8b3afa
Revises: 06448cc316b3
Create Date: 2026-10-03 13:53:36.776009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3b177c8b3afa'
down_revision: Union[str, Sequence[str], None] = '06448cc316b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('price_range')
        batch_op.drop_column('photos')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('price_range', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
